### ISSUE TITLE
HasAssociationValidationRule expects number keys.. Is it right?

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-orm#114]
Hi
having read the source code, I see that the `HasAssociationValidationRule` class setup a validation rule that checks for an `id` property, and that must be a `number`..

That means this plugin can't deal with string foreign keys? 
I have a backend that uses GUID as primary/foreign keys (I'm not happy with this, but it uses RethinkDB, and it is a lot happier with guids than with integers).

Thanks!
P.

**Comment by RWOverdijk** [comment]
@nexbit Another valid point. This plugin was written to work with 0.6.8 of aurelia-validation. When I heard  they were rebuilding it I stopped working on it (and thus never fixed this). Like I said in the other issue I'm looking in to it. Once I find a solution, I'll fix this part, too. Any suggestions are obviously welcome! :)

**Comment by doktordirk** [comment]
obsolete
