### ISSUE TITLE
Make Repository.findPath relative to resource

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-orm#119]
Hi
maybe it's only me, but when I program against a Repository instance, I'd expect every operation bounded to the `resource` path. If I don't want that, I can simply program against the Rest endpoint..

I need the `findPath` method, because my endpoint follows a (very common) REST structure where ids are in the path: `/categories/id`
If there's another clean way to GET a resource by altering the path, then discard the following.

The `findPath` method on Repository feels wrong to me. It simply forwards the path to the underlying Rest endpoint, without prefixing `resource` path:

```
var findQuery = this.getTransport().find(path, criteria);
```

but it can be changed to

```
var findQuery = this.getTransport().find(this.resource + path, criteria);
```

and change the `find` method accordingly:

```
    Repository.prototype.find = function find(criteria, raw) {
      return this.findPath('', criteria, raw);
    };
```

Then I can use the `findPath` method like `repo.findPath('/id')`

**Comment by RWOverdijk** [comment]
findPath is one of the methods that's there to allow you to _change_ the path. The reason for this is because not all routes are relative to the resource (like find is).

It's there in case you want to use the repository for a different path, in stead of find which is relative. I think this makes perfect sense, but I'd love to hear what you think.

**Comment by pfurini** [comment]
For what I understood in the library docs, the repository should be tied to a particular resource, like `users` or `documents` etc.
For that matter I expect that every action I do through a repository is tied to that particular resource. If I want to fiddle with the api _endpoint_ I can program against the underlying `rest` interface of `aurelia-api`...

Having said that, imagine that I have a resource that maps some subpaths to some related entities, like `users/{id}/delegates`. I usually do that when the related entities involves particular server-side effort (like fetching from remote resources).

If `findPath` were relative, I could simply do:

```
this.repository.findPath(`${id}/delegates`);
```

instead I have to do the pretty awkward:

```
this.repository.findPath(this.repository.getResource() + `/${id}/delegates`);
```

For my use case the former is more frequent than the latter, and as I said above if I wanted to program against the endpoint I could simply use the `aurelia-api` rest interface.

Thx,
P.

**Comment by pfurini** [comment]
**UPDATE**: missed a `criteria` parameter in the examples above, because if I want to do a GET to a subresource I can use the `find` method like

```
this.repository.find(`${id}/delegates`);
```

and that works, but I can't do

```
this.repository.find(`${id}/delegates`, criteria);
```

I have to use `findPath` instead, but given that's not relative to the resource I have to do:

```
this.repository.findPath(this.repository.getResource() + `/${id}/delegates`, criteria);
```

**Comment by RWOverdijk** [comment]
@nexbit Then I should update the docs. You shouldn't think in resources for custom repositories, but rather in worker classes. You _could_ use api for that, but that's not the point of [repositories](http://martinfowler.com/eaaCatalog/repository.html). 

We could add a method, to make it easier to find relative to the resource, or refactor find to accept that + criteria. I'd +1 that!.

**Comment by pfurini** [comment]
I see your point, but from a first (quick) analysis of the plugin's sources, it reminds me more the hybrid approach that `breezejs` takes than a pure Repository pattern.. But it can make sense if a repository tied to a model spans different physical resources on the server, even if it's a rare condition in my personal experience.
Your second proposal (refactor `find` to accept a path AND a criteria) maybe it's the way to go, if you see fit.
P.

**Comment by RWOverdijk** [comment]
@nexbit I agree. I like absolute separation.

We'll close this issue, and open up a new one to keep it clean. I'll reference back here.
