### ISSUE TITLE
ValidationRule class no longer exported by aurelia-validation

### ISSUE THREAD

**Issue by bas080** [SpoonX/aurelia-orm#121]
https://github.com/SpoonX/aurelia-orm/blob/master/src/validator/has-association.js#L4

**Comment by pfurini** [comment]
@bas080 That's expected, I fear. This library is compatible with 0.6.x version, and certainly not with the latest beta one.

Please see this [issue](https://github.com/SpoonX/aurelia-orm/issues/114) and this comment in other [issue](https://github.com/SpoonX/aurelia-orm/issues/96#issuecomment-225600709)

If you want to use this library today you have to stick with `aurelia-validation` 0.6.8, or get rid of the dependency manually like I did in my fork.
(DISCLAIMER: not the author here..)

**Comment by RWOverdijk** [comment]
@nexbit @bas080 Is part of our team. I asked him to make this issue :)

We're working on a solution, which involves some work. We've almost come to an agreement.

**Comment by doktordirk** [comment]
fixed
