### ISSUE TITLE
Make deleting the id field before an update request optional

### ISSUE THREAD

**Issue by CuddleBunny** [SpoonX/aurelia-orm#185]
I usually design my PUT api like so:

```
[HttpPut]
public async Task<JsonResult> Put([FromBody] T item) {
    // ...
}
```

but after seeing the HTTP traffic from this plugin I had to change it to:

```
[HttpPut("{id}")]
public async Task<JsonResult> Put([FromRoute] Guid id, [FromBody] T item) {
    item.Id = id;
    // ...
}
```

See this thread if more context is needed: https://github.com/SpoonX/aurelia-api/issues/151

**Comment by doktordirk** [comment]
yeah, i'm not sure about that in the current setup. aurelia-orm is currently only using aurelia-api (better named aurelia-rest), so for restful webservices. and there the id is part of the path. i'd rather recommend to design your api backend to be restful

**Comment by RWOverdijk** [comment]
What is this syntax?

**Comment by CuddleBunny** [comment]
I can respect that if everyone wants to keep it strictly in line with typical REST implementations. Would it be against the standard too much to still send the ID with the URL but (perhaps optionally) not delete it from the request body?

@RWOverdijk The code above is from ASP.NET MVC 6, it was just meant to illustrate how much more verbose the ID Route implementation is.

**Comment by doktordirk** [comment]
i think the idea is to replace the update with updateOne(resource,id,..). that actually might help, since it.ll be easy to replace the updateOne of the used api instance with a custom one

**Comment by doktordirk** [comment]
@CuddleBunny there is also removeCollectionAssociation which uses like:
destroy('/users/1/comments/2')
so, how do you do that in your setup?

**Comment by CuddleBunny** [comment]
If my goal is to delete the comment entirely i would just: 

DELETE: /api/comment
[Body]
{ id: 2 }

If I was disassociating the comment from the user without deleting it would be like:

PUT: /api/comment
{ id: 2, userId: null }

All of my association collections on the server side are convention based, so just nulling out the foreign key will remove if from the collection.

**Comment by doktordirk** [comment]
hmm. still might be easier/possible, when we allow other transports than aurelia-api. for now, you'd have to fixup your own aurelia-api to convert the path/body

**Comment by CuddleBunny** [comment]
I've just been rolling with it, but if anyone finds this and doesn't want to roll with it, simply deleting the line: `delete requestBody[this.getIdProperty()];` from Entity.js would probably work.

**Comment by gregoryagu** [comment]
@CuddleBunny I am with you on this one.  The Id should be included in the post as well. It a bit odd to pull the Id from the route and then put it back in the entity. Using aspnetentitycore.  But, like you say, the workaround is pretty easy.

**Comment by RWOverdijk** [comment]
If I understand correctly, the issue here is that the null value doesn't get persisted to the server? Because that's an easy fix, as you already found. (sorry for the late reply, there was a slight transition in the team and this issue got overlooked).

**Comment by CuddleBunny** [comment]
The issue is just that I believe the id property should not be deleted from the request body.

**Comment by RWOverdijk** [comment]
Right, and I'm pretty sure that can be done safely. I do agree it should perhaps be an option that can be configured somewhere. I can take a look some time in the future (a bit busy) but if you feel like it, you can make a PR as well. :)
