### ISSUE TITLE
Calling entity.reset() unbinds bound properties

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#191]
I have no idea why, but after calling reset() on an entity, the binding that aurelia sets up no longer works.

What I am trying to do is revert any changes that a user has made if he decides to cancel his updates.

Reset does reset the original values, but the binding is lost.

**Edit**
I found this and it appears to work:

   `this.currentItem.setData(this.currentItem.__cleanValues.data.entity);`

**Comment by RWOverdijk** [comment]
@gregoryagu That's because the values get replaced. There are cases where it otherwise won't work.

I wish to refactor all of this, but Proxies don't work (yet) without dirty checking. I suppose we could dynamically generate proxies based on the entity, but then they can't be dynamic anymore.

**Comment by gregoryagu** [comment]
@RWOverdijk Ok.  I am going to close this, as it is resolved for me at this time.

**Comment by Kukks** [comment]
Re-opening this as I've run into this issue and when using typescript, I get compiler errors with the mentioned workaround since `__cleanValues` is not exposed in the dts.

**Comment by RWOverdijk** [comment]
@Kukks a PR that implements a clear using the workaround would be welcome :)
