### ISSUE TITLE
Is it possible to extend Entity?

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#197]
I would like to extend Entity:

```
export class EntityBase extends Entity{

    foo(){
    ....
   }

}
```

It is possible to register this as the base class so that all Entities produced have .foo()?

**Comment by doktordirk** [comment]
sure. with Entity.prototype.foo = function(){..}

**Comment by gregoryagu** [comment]
I should have known that Dr Dirk.
