### ISSUE TITLE
association-select ignores placeholder value

### ISSUE THREAD

**Issue by mredl** [SpoonX/aurelia-orm#202]
In rc7 of aurelia-orm, the association-select ignores a custom placeholder value. i have set following properties, but in the final html code always '- select a value -' gets rendered as placeholder.

`
 <association-select property="name"
                                    value.bind="currentStudioId"
                                    repository.bind="studioRepo"
                                    selectablePlaceholder="true"
                                    criteria.bind='{where:{isAvailable:{"==":true}}}'
                                    placeholderText="Select Studio">
                </association-select>
`

**Comment by doktordirk** [comment]
see https://github.com/SpoonX/aurelia-orm/pull/213
