### ISSUE TITLE
Calling save() on included entities

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#218]
I have an entity called customer, with related orders.

When I get a customer, I get the open orders at the same time.

This works fine to fetch the items.

However, if I then want to call save on an order, it is not of type entity, so there is no save function.

So how should I go about saving the order?

Or should I be making two calls to the server, once for the customer, and once for the orders? I would prefer to just make one call.

**Comment by doktordirk** [comment]
why isn't your order not of type entity? One would expect that order extends entity

**Comment by glyad** [comment]
Hi,

It was a great question! The save() method as a member of an Entity seems like as violation of single responsibility principle. IMHO, the Entity must be statefull class with Dirty state tracking. All of CRUD or another manipulation methods must be implemented in an "mediator" class. I call it "Service", e.g. LoginService, DataService, etc. So, a service can know all of the entities and serves as Single Source of True for a whole MVVM app.

**Comment by doktordirk** [comment]
i also had some concerns there (don't remember which though). but i'm not that great with all those concepts, so @RWOverdijk wanna chip in?

**Comment by gregoryagu** [comment]
@glyad I find the save() method on the entity extremely useful.  For example, I have a list of items in the UI, and a save button for each with .save(item) bound to the click event.  Then when my viewmodel receives the item, is is very easy to call item.save().

There is no reason why the entity can't be responsible for updating itself - I don't see this as a violation of single responsibility.  Anyhow, just my opinion.

As far as my original question is concerned, @doktordirk was correct.  I was missing the association decorator on the related objects.  So as far as I am concerned, this can be closed.
