### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by mifp** [SpoonX/aurelia-orm#219]
Getting a dependency error when building. Trying to find a typer.js file, which doesn't exist. Could someone enlighten me? Not sure what I am doing wrong.

{ [Error: ENOENT: no such file or directory, open 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js',
     moduleTree: [ 'aurelia-orm/aurelia-orm' ],
     fileName: 'C:/Users/Mi/Desktop/accutics_app_design/node_modules/aurelia-orm/dist/amd/aurelia-orm.js' },
  duration: [ 5, 676095337 ],
  time: 1474102958625 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { [Error: ENOENT: no such file or directory, open 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js',
     moduleTree: [ 'aurelia-orm/aurelia-orm' ],
     fileName: 'C:/Users/Mi/Desktop/accutics_app_design/node_modules/aurelia-orm/dist/amd/aurelia-orm.js' },
  duration: [ 5, 990886970 ],
  time: 1474102958636 }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\Users\Mi\Desktop\accutics_app_design\src\typer.js',
  moduleTree: [ 'aurelia-orm/aurelia-orm' ],
  fileName: 'C:/Users/Mi/Desktop/accutics_app_design/node_modules/aurelia-orm/dist/amd/aurelia-orm.js' }

**Comment by doktordirk** [comment]
that's webpack or cli?

**Comment by mifp** [comment]
Oh, sorry. Forgot to mention. It is CLI

**Comment by doktordirk** [comment]
try adding "typer" to the aurelia.json

**Comment by mifp** [comment]
That was it! Thank you :)
