### ISSUE TITLE
Association decorator not working for me

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#223]
I have an entity called "Item"

Item has a collection of items called Children.  I have decorated it like so:

```
@association({collection: 'children'})
children: Array<Item>;
```

I have made sure that on the server side, the collection is called "children"  I have checked in the debugger and it shows the names are correct.

However, only the root object gets asObject() called it by the ORM.  The children are just POJO's.

When I look in the debugger, I can see properties such as __cleanValues on the root object, but not the items in the child collection.

Thus, I cannot call save on a child item.  I get an error message saying method save() is not defined.

This is the call the gets the data:

```
`this.repository.find("getTopLevelItemAndChildren");`
```

Is there something else I need to do?

Or should I be calling save only on the root object?

**Comment by doktordirk** [comment]
any entity must be of type Entity.

**Comment by gregoryagu** [comment]
Item is of type Entity.   In other words, I have subclassed Entity in the class definition of Item.

If I get an item, with no children, then I can call save on the Item and it saves it as expected.

I just don't understand how I am supposed to save changes to the child entity.  Am I supposed to call save on the child?  Or call save on the parent?

I was trying to call save on the child, because the hierarchy is 5 levels deep, and calling save on the root object didn't seem correct.  The data is  part of a treeview which has a root object and each node is a child of the root.

**Comment by doktordirk** [comment]
both should do it (if set up that way). with parent.save() on that parent is saves on parent/id/child/id (resource parent) and with parent.child[id].save() on the child on child/id (resource child). the later accessed through the parent as well, since it was loaded into parent.child[id] which is a different object from child loaded directly
