### ISSUE TITLE
Associations not working for me

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#233]
I have an entity called "Item"  It has an association called "comments".

When I fetch an "Item" I would expect it to also fetch the comments, but it does not.

I have stepped through `getPopulatedEntity` and the issue seems to be with the metadata - no metadata is found for the comments property.

This is the code in Typescript:

```
export class Item  extend Entity {
    id: number;

    @association('comment')
    comments: Array<Comment>;
}
```

Have also tried:

```
@association({collection: 'comment'})
 comments: Array<Comment>;
```

This is the js that is produced by TypeScript:

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
define(["require", "exports", 'aurelia-orm', 'aurelia-orm'], function (require, exports, aurelia_orm_1, aurelia_orm_2) {
    "use strict";
    var Item = (function (_super) {
        __extends(Item, _super);
        function Item() {
            _super.apply(this, arguments);
        }
        __decorate([
            aurelia_orm_2.association('comment'), 
            __metadata('design:type', Array)
        ], Item.prototype, "comments", void 0);
        return Item;
    }(aurelia_orm_1.Entity));
    exports.Item = Item;
});
```

**Comment by doktordirk** [comment]
is the comment of type Entity?

also it's getPopulatedEntity(data:{}, entity?:Entity). meaning does the data contain the association data?

**Comment by gregoryagu** [comment]
Yes, comment is of type Entity.

Yes, when I get an item from the database, it includes the comments. 

The issue is with the Metadata as when this code is run, `entityMetadata` does not include the associations.

```
if (!entityMetadata.has('associations', key) || (typeof value === 'undefined' ? 'undefined' : _typeof(value)) !== 'object') {
          populatedData[key] = value;

          continue;
        }

        //This code never runs as no associations were found. So the comments are POJO's.
        var _repository = this.entityManager.getRepository(entityMetadata.fetch('associations', key).entity);
        populatedData[key] = _repository.populateEntities(value);
```

**Comment by gregoryagu** [comment]
I have also stepped through the code that saves the collection, but that also doesn't find the associations in the metadata.

**Comment by doktordirk** [comment]
can you give me some details on ts version, npm or jspm ...

**Comment by gregoryagu** [comment]
TS 2.0.2.0
using jspm
"aurelia-orm": "npm:aurelia-orm@3.0.0-rc7",

I created a brand new project using latest typescript skeleton and followed the instructions in the tutorial to the letter, and I still get the same result - the metadata is not being found and used.

I stepped through builder.regsterEntities() and it seems to run ok.

```
.plugin('aurelia-api', config => {
          config
              .registerEndpoint('item', 'http://localhost:56185/api/')
              .setDefaultEndpoint('item');
      })

      // Register the plugin, and register our entities.
      .plugin('aurelia-orm', builder => {
          builder.registerEntities(entities);
      })

import { Entity, repository } from 'aurelia-orm';

export class Comment extends Entity {
    id:number;
    content: String;
}

import { type, association, Entity } from 'aurelia-orm';

export class Item extends Entity {

    id: number;

    test: string;

    name: string;

    @type('Date')
    date: Date;

    @association('comment')
    comments: Array<Comment>;

}

let awaitResponse = this.itemsRepository.find();
      return awaitResponse.then(
          items => this.items = items);

```

When the items are returned, the "Item" has the extra properties of an entity, but Comment is just a POCO.

**Comment by doktordirk** [comment]
try withòut 's'

``` js
    @association('comment')
    comment: Array<Comment>;
``
```

**Comment by gregoryagu** [comment]
I tried without the s

export class Item extends Entity {

```
id: number;

test: string;

name: string;

@type('Date')
date: Date;

@association('comment')
comment: Array<Comment>;
```

}

Still, same result.  Both Item and each comment in both do not have any metadata.  The issue is that the metadata is not being processed.  The metadata of item is missing the metadata of the fact that the Date is of type "Date" and it is missing the fact that there is an association.

The metadata looks like this in the debugger:

```

        repository: DefaultRepository,
        resource: null,
        endpoint: null,
        name: null,
        idProperty: 'id',
        associations: {}

```

If I put a resource decorator on the Entity, the resource property of metadata is still empty:

@resource('my-endpoint')
export class Item extends Entity {

```
id: number;

test: string;

name: string;

@type('Date')
date: Date;

@association('comment')
comment: Array<Comment>;
```

}

So none of the decorators are being passed to the metadata.

**Comment by doktordirk** [comment]
which brings be back to the question which typescript version you are using. i know there is an issue with property decorators in babel. 

i tried with my simple sample https://github.com/doktordirk/aurelia-orm-loopback-sample/tree/master/client-ts and seems to work. maybe compare it to your settings

**Comment by gregoryagu** [comment]
I was able to get the Loopback Typescript sample working and all the metadata is working fine.  I will work with this some more and see if I can find the difference my project and the Loopback sample.  

To answer your question, I am using Typescript 2.0.2 which is the latest version at the moment.  Also, not using Babel.

 Thank you very much for the support.

**Comment by gregoryagu** [comment]
I can now duplicate the issue I was having in the Loopback sample.

This is how the sample looks:

```
@resource('user')
export class User extends Entity {
    displayName: string = '';
    email: string = '';
    password: string = 'none';

    @association('customer')
    customers: Array<Customer> = null;
}
```

This works fine to load the association metadata, and turn the customers into Entities.

However, if you remove `@resource('user')` the metadata for the association will fail to load.  

According to the documentation, because the resource is exactly the same as the class name, it should not be necessary.  But it is.  I have tested this on two different projects and the outcome is the same - the metadata attributes do not get processed if the resource decorator is omitted.

However, on the customer class, I can remove the resource decorator and User and it's customers load the metadata just fine.  It seems to be the root item (`User` in this case) that requires the resource decorator.
