### ISSUE TITLE
TypeError: Cannot read property 'customRule' of undefined - ORM 3.0.0

### ISSUE THREAD

**Issue by jeremyvergnas** [SpoonX/aurelia-orm#236]
Got the following error with aurelia-orm@3.0.0
TypeError: Cannot read property 'customRule' of undefined

Works fine with aurelia-orm@3.0.0-rc7

**Comment by doktordirk** [comment]
you have aurelia-validation 0.12+ installed and initialzed?

**Comment by doktordirk** [comment]
@jeremyvergnas that's still valid?

**Comment by jeremyvergnas** [comment]
No, it is not valid anymore. Sorry, can be closed.
