### ISSUE TITLE
Question: How do I pass options to the base fetch?

### ISSUE THREAD

**Issue by devingoble** [SpoonX/aurelia-orm#242]
If I were writing directly against fetch I would be able to pass CORS options using mode. Is there a way to do this with aurelia-orm (or possibly the underlying aurelia-api)?

**Comment by doktordirk** [comment]
with aurelia-api you can set options on configuration eg 
{name: 'weather', endpoint: 'https://weatherapi.io/', config: {headers: {x: 'foo'}}},

https://github.com/SpoonX/aurelia-api/blob/master/doc/configuration.md
