### ISSUE TITLE
Association-select not selecting values

### ISSUE THREAD

**Issue by VMBindraban** [SpoonX/aurelia-orm#278]
In chrome 57, safari 10, firefox 49 and firefox 52 `association-select` is not selecting the given values.

Chrome 56 worked fine however.

**Comment by RWOverdijk** [comment]
You mean the default value?

**Comment by RWOverdijk** [comment]
https://swan-example.spoonx.org/#/association-select Works fine for me. Maybe you're doing something wrong. Do you have some example code?

**Comment by VMBindraban** [comment]
The example doesn't load a default value.

**Comment by RWOverdijk** [comment]
It does for me. Linux, by any chance? Is it chrome or chromium?

**Comment by VMBindraban** [comment]
Nope, Mac with google chrome. Chrome 56 worked fine. This problem occurs on 3 different machines. Could be a dependency that broke it.

**Comment by RWOverdijk** [comment]
@VMBindraban I have to ask.. If you wait a while, does it then work? The swan example runs a free backend, so maybe the server needs to wake up first.

Chrome Version 57.0.2987.110 (64-bit)

<img width="1173" alt="screenshot 2017-03-20 10 34 19" src="https://cloud.githubusercontent.com/assets/781745/24094399/cd8384e0-0d58-11e7-990d-4c8da645bb22.png">

**Comment by RWOverdijk** [comment]
Firefox 49.0.2

<img width="1169" alt="screenshot 2017-03-20 10 35 29" src="https://cloud.githubusercontent.com/assets/781745/24094439/feee6bbc-0d58-11e7-8955-652143543a8e.png">

**Comment by RWOverdijk** [comment]
Firefox 50.1.0

<img width="1171" alt="screenshot 2017-03-20 10 36 51" src="https://cloud.githubusercontent.com/assets/781745/24094473/266dcb56-0d59-11e7-9d3f-60a2a2578257.png">

**Comment by VMBindraban** [comment]
I know, the swan-example does not have this problem because there is no selected value.
It looks like the same problem as we had with the translate bug. https://github.com/SpoonX/aurelia-orm/pull/238

If i place a `valueChanged` in the `association-select` and console.log that it fires twice, one with the selected value and with a empty array. To make the problem weirder, it did work for me (Chrome 56) untill i updated to 57 (because it didn't work for @jeremyvergnas initially)

**Comment by RWOverdijk** [comment]
Ah, defaultValue... Fair enough.

**Comment by RWOverdijk** [comment]
Closing this because of the amount of time that has passed.
