### ISSUE TITLE
Does this ORM adhere to a specific API spec?

### ISSUE THREAD

**Issue by cottrellio** [SpoonX/aurelia-orm#279]
Other frameworks with data-layers, like EmberJS, adhere to a common spec like JSON-API (http://jsonapi.org/). Just wondering if there is a spec I can reference that will play nice with your ORM.

**Comment by RWOverdijk** [comment]
This orm doesn't really follow a spec (it probably should). It works ootb with APIs such as sails or loopback.

I would like to use this issue as a starting point to discus adapter logic. Specs, local, and the one we use right now.
