### ISSUE TITLE
Will this ORM work with aspnet core based "web API" back end

### ISSUE THREAD

**Issue by adriatic** [SpoonX/aurelia-orm#280]
While I expect that the answer will be yes, I would like to know that this was a tested scenario.

**Comment by RWOverdijk** [comment]
@adriatic I know of some people using it for that. I haven't tested this personally, though.

**Comment by adriatic** [comment]
Thanks, @RWOverdijk. I will definitively try to use it in a project that is common for Aurelia and Auth0 community (in the context of Aurelia full stack apps in the need of Authentication and Authorization).

I will not use **[aurelia authentication](https://github.com/SpoonX/aurelia-authentication)** plugin because I do not like the idea of "stuffing" Auth0 PaaS into a wraper designed for Satellizer. Actually, I do not want to use any wrapper for Auth0.

Let me know if you are interested in participating in this project in any way, please.

**Comment by RWOverdijk** [comment]
@adriatic Fair enough, I understand your preference.

I'm not sure in what way you'd like me to participate in this project. Setting up an example, you mean? Because I'm currently not interested in working with aspnet.

**Comment by adriatic** [comment]
No example work, Wesley - this was meant to be a task in the "schmoozing" category (read: I wanted to introduce you to other folks as the aurelia-orm developer). As there will be time for this if my effort results with something non-trivial, feel free to disregard this.

**Comment by RWOverdijk** [comment]
Ah! Yes, absolutely that's fine.

**Comment by adriatic** [comment]
Thank you - you should find the invitation to https://github.com/aurelia-auth0 GitHub organization, being assigned the role of an adviser, together with Rob Eisenberg, who was very supportive of the idea to include you here. Feel free to get in touch with me via email or in https://gitter.im/RWOverdijk for any "out of band" communications.

**Comment by RWOverdijk** [comment]
👍  I'm closing this issue for now.
