### ISSUE TITLE
Aurelia CLI configuration

### ISSUE THREAD

**Issue by Kukks** [SpoonX/aurelia-orm#281]
It seems that when using this plugin along with aurelia cli, it tries to load association-select.js and paged.js from the node_modules folder even though it should have been bundled. The website does not load at all when built for the default prod environment without a relative node_modules folder.

I've fixed it for the time being by using the following config in aurelia.json

```
            "name": "aurelia-orm",
            "path": "../node_modules/aurelia-orm/dist/amd",
            "main": "aurelia-orm",
            "resources": [
              "component/association-select.html",
              "component/paged.html",
              "component/association-select.js",
              "component/paged.js"
            ]
```

**Comment by RWOverdijk** [comment]
@Kukks That's the way it works right now. I don't know how we could improve that. Adding it to our own resources in package json? If so, would you like to submit a PR?

**Comment by Kukks** [comment]
@RWOverdijk The installation guide only says you need the html files under resources. Should it reflect my config instead?

**Comment by RWOverdijk** [comment]
@Kukks I'm pretty sure we just have to add it to our resources. Recently the same was done for aurelia-form: https://github.com/SpoonX/aurelia-form/pull/192

**Comment by jasoncarreira** [comment]
I'm still getting an error, even with this config:

'Error: File not found with singular glob: /Users/jason/projects/your-deferrals/node_modules/aurelia-orm/dist/amd/component/association-select.html'
