### ISSUE TITLE
Overriding what determines a 'new' object? 

### ISSUE THREAD

**Issue by gerfen** [SpoonX/aurelia-orm#282]
I have system which uses GUID as the primary key for entities.  When I create a new entity it gets an an empty GUID  -'00000000-0000-0000-0000-000000000000'.  When I try to save one of my new entities via Entity.Save(), PUT is used instead of POST.  Is there an easy way for me to override this behavior?

**Comment by RWOverdijk** [comment]
@gerfen When the client-side entity has an ID, it's an existing resource and it's __not__ considered new. Generally, you'd specify those server side (I strongly recommend doing that for many reasons).

At this time, the only way to define the PK client side, is by using the transport yourself. Here's an example:

```js
// A name you pick. I chose BaseEntity for this example.
class BaseEntity  extends Entity {
  constructor() {
    super();
  }

  isNew() {
    // Your own implementation for deciding what _new_ means.
  }
}
```

Then let your entities extend this class, instead of Entity.

**Comment by gerfen** [comment]
@RWOverdijk  Thanks for the quick response.  This is a good idea but unfortunately when I add my own implementation in an extended class,  isNew() is not called when save() is called on the Entity.  If I cast to my implementation, then I am not able to call save().  For now I've forked the code and changed the implementation of isNew() appropriately: 

isNew() {
      let id = this.getId();
      if (id !== undefined && id !== null && id === '00000000-0000-0000-0000-000000000000') {
        return true;
      }
      return !this.getId();
    };

I see there are other parts of the code in entity.js where "!this.getId()" is used to make processing decisions.  Do you have any recommendations about other changes I might need to make to account for having a non-null "id" which represents a new entity?  I suppose I will find out as I continue my testing. 

Thanks for any advice.

--Michael

**Comment by RWOverdijk** [comment]
@gerfen Are you sure? _Your_ `isNew()` has to be called this way. That's how inheritance works.

I do not, no. I can only recommend to not proceed with your approach. Sorry.
