### ISSUE TITLE
Add view-manager

### ISSUE THREAD

**Issue by jvkassi** [SpoonX/aurelia-orm#283]
Hi !

Can you also add a aurelia-view-manager for handling views ?
I want to customize 'association-select.html' .

Great work !

**Comment by RWOverdijk** [comment]
Hello @mib4fun, that's the plan, yeah.  Would you like to give it a go? :) It's not difficult to do and would help a lot (I'm a bit short on time, as everyone seems to be nowadays haha).

**Comment by jvkassi** [comment]
yeah, nowadays :smile: 
I have looked up the code. 
It's doable even by me ^^

But can you guide me a bit ?
What is the best way to test my modifications locally without bundling ?

**Comment by RWOverdijk** [comment]
@mib4fun Sure, are you on gitter? Hit me up in our channel https://gitter.im/SpoonX/Dev
