### ISSUE TITLE
Null float entity field converts to NaN on client

### ISSUE THREAD

**Issue by Avekonst** [SpoonX/aurelia-orm#289]
I've created entity class with @type('float') fields. When I firstly get instance of this entity I don't fill some of this fields, save it and then try to reload. While entity populates on client "typer" try to cast float by 'parseFloat' function so in case of null it returns NaN, but for other types null. Aurelia binding goes into an infinite loop while it tries to compare old and new NaN values (newValue !== oldValue - return true if both NaN).

**Comment by RWOverdijk** [comment]
Oh wow, that's nasty. This doesn't belong here though, so I moved it. :) https://github.com/SpoonX/typer/issues/2
