### ISSUE TITLE
Allow configuring/using FetchClient in aurelia-api

### ISSUE THREAD

**Issue by mreiche** [SpoonX/aurelia-orm#297]
I have already a configured FetchClient for CORS and CSRF-Projection.
Aurelia-ORM should use this FetchClient instead of creating a new one.

**Comment by RWOverdijk** [comment]
Quickly resolved :)

**Comment by mreiche** [comment]
Yes ;) I moved it to aurelia-api https://github.com/SpoonX/aurelia-api/issues/200
