### ISSUE TITLE
entityManager.getEntity not working with string in production mode

### ISSUE THREAD

**Issue by natrim** [SpoonX/aurelia-orm#298]
Hello,

i have TS project with webpack 2.

when i use entityManager.getEntity('user') it works in dev mode, but after compile it breaks
i need to use entityManager.getEntity(User) ie. the function class directly

seems to be caused by minification, because the User gets renamed to t and the aurelia-orm seems to not find the class from string "user" afterwards

**Comment by RWOverdijk** [comment]
@natrim As described in the readme, you need to set the name of the entity in your decorators when using aggressive minifying processes: https://github.com/SpoonX/aurelia-orm#bundling
