### ISSUE TITLE
Registering an entity without the @resource() decorator leads to invalid meta data

### ISSUE THREAD

**Issue by mreiche** [SpoonX/aurelia-orm#300]
The documentation about the ``@resource()`` decorator says
> This decorator is probably the most important one.

But this decorator is never mentioned in the whole Quickstart or Entites guide https://aurelia-orm.spoonx.org/entities.html

Fact is: without the decoratory, the entitymanager doesn't has meta data for this entity. This is a documentation bug.

**Comment by RWOverdijk** [comment]
Resource should have the name of the resource because minification will otherwise mess things up.

But yes, it could use more docs! :)

**Comment by mreiche** [comment]
Minification removes the ``@resource()`` decorator completely?

**Comment by RWOverdijk** [comment]
@mreiche No, it renames classes. And without a value, the decorator uses the name of the class. Minification can still work if you disable renaming. Check the bottom of the readme for more info.

**Comment by mreiche** [comment]
Ok, I add that to the documentation.

**Comment by RWOverdijk** [comment]
@mreiche Yeah it can be added with the decorator itself. I agree. Thanks!
