### ISSUE TITLE
Question: How to use path parameters?

### ISSUE THREAD

**Issue by mreiche** [SpoonX/aurelia-orm#307]
Is it possible to define and use path parameters in custom find methods?

```javascript
repository.find('/articles/{article}/editors',{article:1}).then(editors=>{

});
```

**Comment by RWOverdijk** [comment]
No, it is not. You're looking for criteria, [findPath](https://github.com/SpoonX/aurelia-orm/blob/master/src/repository.js#L135), or direct access to aurelia-api.

But to me it sounds like you want to look for /editor?article=1

**Comment by mreiche** [comment]
Ok, the real issue is, that findPath() is undocumented here https://aurelia-orm.spoonx.org/api_repository.html

**Comment by RWOverdijk** [comment]
@mreiche I agree. That's a problem....
