### ISSUE TITLE
Possible to auto-generate Aurelia ORM definition from Django model?

### ISSUE THREAD

**Issue by brylie** [SpoonX/aurelia-orm#308]
When designing a client/server application, it would be nice to maintain the data model in only one place, rather than having models defined on both client and server.

Out of curiosity, how might Aurelia ORM definitions be auto-generated from a server codebase, such as Django models?

What would be the general concepts involved in serializing a model definition from a server codebase, and de-serializing/using it in the Aurelia framework?

**Comment by RWOverdijk** [comment]
@brylie Everything could be generated on the fly. I started working on that and used it. I also deleted it again because it was a bad idea. Client and server are just too different.
