### ISSUE TITLE
Sending parameters as path separated with "/"

### ISSUE THREAD

**Issue by imboden** [SpoonX/aurelia-orm#309]
Hello,

Is it possible that parameters sent via the .find() method are sent to the REST WebService as "path" and not parameters?

So not like : 
my_url/id=1&value=2&somethingElse=3 
but
my_url/1/2/3

Thanks

**Comment by RWOverdijk** [comment]
Sure, use findPath. https://github.com/SpoonX/aurelia-orm/blob/master/src/repository.js#L135
