### ISSUE TITLE
Updating Related Items

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#311]
I am trying to understand how related items is supposed to work when they are updated.

For example, I have an entity called `myEntity` with a property called `statusId`, and an entity property called `status`.

So now, in the UI, I want to change the status.  So in my dropdown, I have it bound to a list of statusTypes.

So when the user selects a new status, the new status entity is assigned to the myEntity.status.

But myEntity.statusId has not changed, so if the entity is saved, then the id is not updated.

Is there a way to use the association decorator to make this automatically happen?

The way I am actually doing it right now is to bind directly to statusId in the dropdown, and then before any save, I manually find the correct status entity and assign it to myEntity.status so the UI shows the correct data.

But I think I am not correctly wiring this up.

**Comment by RWOverdijk** [comment]
When using the association decorator, changing relations should be marked as dirty and automatically allow you to flush changes. When validating, the entity gets flattened, meaning relations get replaced by ids to check if they changed.

This only works when it's a clear relationship (using the `@association` decorator) and the target entity has a primary key value (`id`) to use.

**Comment by gregoryagu** [comment]
Thank you so much.
