### ISSUE TITLE
Endpoint decoration dont seems to work

### ISSUE THREAD

**Issue by ShauniArima** [SpoonX/aurelia-orm#312]
I want to use aurelia orm with differents endpoints. But when I use the `endpoint` decorator, it keep the default endpoint.
So, I have two files.

* `myEntity.js`
```
import {Entity, repository, resource, idProperty, type, association, endpoint, validatedResource} from 'aurelia-orm';
import {ValidationRules} from 'aurelia-validation';
import MyRepository from 'services/repositories/incident';

@endpoint('my-service')
@validatedResource()
@repository(MyEndpoint)
@resource('my-entity')
@idProperty('id')
export default class MyEntity extends Entity {
    // Some attributes and default constructor
}
```

* `myRepository.js`
```
import {Repository} from 'aurelia-orm';

export default class MyRepository extends Repository {
}
```

And `aurelia-api` is configured like this:
```
endpoints: [
    {name: 'an-api', endpoint: 'http://an-api-endpoint.com/'},
    {name: 'my-service', endpoint: 'http://my-url.com/my-service/'}
],
defaultEndpoint: 'an-api'
```

Regards,

**Comment by ShauniArima** [comment]
My bad, I have made a mistake on my call.

**Comment by ShauniArima** [comment]
So, I'm sorry but I have changed my defaultEndpoint. So that work but, if I change default endpoint, that do not work.

**Comment by RWOverdijk** [comment]
That should work... Odd. Are you getting the entity by the proper reference? If not, a default will be constructed for you and won't red your definition.

**Comment by RWOverdijk** [comment]
Closing this because of the amount of time that has passed.
