### ISSUE TITLE
Initializing the Repository.

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-orm#317]
This is really minor, just a question:

This is from the docs and of course it works:

```
@inject(EntityManager)
export class SomeViewModel {
  constructor (entityManager) {
    let repository = entityManager.getRepository('user');

    repository.find({username: 'bob'})
      .then(result => {
        console.log('Found User!', result);
      });
  }
}
```

But, what I would really like to be able to do is inject the Repository from D.I. without have to go through the step of `let repository = entityManager.getRepository('user');`

Like this:

```
@inject(UserRepository)
export class SomeViewModel {
  constructor (userRepository) {
    
     repository.find({username: 'bob'})
      .then(result => {
        console.log('Found User!', result);
      });
  }
}
```

I have tried this, but the metadata is missing, and so exceptions are thrown.  Maybe there is some one to initialize the Repository in the custom class itself:

```
import {Repository} from 'aurelia-orm';

export class Custom extends Repository {

     constructor(){
      //Initialize here
     }

}
```

**Comment by RWOverdijk** [comment]
@gregoryagu that would be really cool. I'm currently implementing that exact feature for a different project.

Do you dare take this on? 😄

**Comment by gregoryagu** [comment]
Yes, I would be happy to, as long as you give me a little guidance.  I will review and then propose what I think should be done. Then you can review and let me know if I am on the right track.  Sound good?

**Comment by RWOverdijk** [comment]
I would love to, but there's a reason I'm not working on these plugins as much as I used to. I can try to find some time in between to help out. And I think I mentioned it before, but you can also join me on slack where chances of me replying are greater haha.

**Comment by gregoryagu** [comment]
ok, sounds good.  You are on aurelia-js.slack.com?  I tried registering there, but it is asking me for an @aurelia.io, @bluespireconsulting.com, or @verizondigitalmedia.com email address,

What is it your are working on these days?

**Comment by RWOverdijk** [comment]
I'm here: https://spoonx-slack.herokuapp.com/
