### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by joncarlson** [SpoonX/aurelia-orm#39]
Unless there already is a way I'm not seeing, but would be nice to see the ability to add custom actions. 

For example, if I wanted to add an `authenticate()` action to an entity.

**Comment by RWOverdijk** [comment]
@joncarlson Custom lookups can be added to repositories. Methods such as authenticate don't belong on entities, but in stead should be placed elsewhere. For your specific case, you could use [aurelia-auth](https://github.com/SpoonX/aurelia-auth).

**Comment by RWOverdijk** [comment]
I'm closing this. Let me know if this answer wasn't enough :)

**Comment by joncarlson** [comment]
@RWOverdijk thanks! I did switch authentication to aurelia-auth instead.

Out of curiosity, are there docs or examples for the custom lookups?
