### ISSUE TITLE
How to display validation messages during inputing forms 

### ISSUE THREAD

**Issue by masteriusz** [SpoonX/aurelia-orm#55]
I might be missing something, but how do I achieve the same functionality as with the pure aurelia-validation? I want to show the user real-time input validation messages, not only validate during submiting the form. I'm looking for a solution that doesn't require to duplicate code (such as one set of validation rules in the entity and another one strictly for showing messages inside the form) Let's say I have a **customer entity**:
`@validatedResource('customers')`
`export class Customer extends Entity {`
`@ensure(it => it.isNotEmpty().hasLengthBetween(1, 20))`
`name = null;`
`}`

And somewhere in the app I'm using it in a form:
**newcustomer.html**
`<button click.delegate="save()" >`
`Save  </button>`
`<form validate.bind="validation" role="form">`
`<div class="form-group">`
`<label>Name</label>`
`<input type="text" placeholder="Name and Surname" class="form-control"`
 `value.bind="customer.name" />`
`</div>`
`</form>`
**newcustomer.js**
....
`@inject(EntityManager)`
`export class newcustomer {`
`constructor(entityManager) {`
`this.customersRepository = entityManager.getRepository('customers');`
`this.customer      = entityManager.getEntity('customer')`
`}`
`save() {`
`this.customer.getValidation().validate().then( () => {`
`console.log("I updated"+ this.customer.name);`
`return this.customer.save()`
`} )`
`};`
By default aurelia-validation would attach messages to the <label> such as _is required_ or _length has to be between x and y_. 
Thanks for any help!

**Comment by doktordirk** [comment]
was that answered with RWs quick answer on gitter?

**Comment by RWOverdijk** [comment]
@masteriusz You'll probably need the `validate=""` property because it's an instance.

**Set validation from `entity.getValidation()`**
`<form validate.bind="validation"></form>`

**Use the name of the property to validate:**
`<input validate="name">`

**Comment by RWOverdijk** [comment]
@masteriusz I'm closing this issue. But if you still have any questions, feel free to comment!
