### ISSUE TITLE
component test

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#59]
add my simple component test to prevent issues like https://github.com/SpoonX/aurelia-orm/pull/57

**Comment by doktordirk** [comment]
template for this https://github.com/doktordirk/aurelia-facebook/tree/master/test

**Comment by doktordirk** [comment]
started https://github.com/SpoonX/aurelia-orm/pull/57

**Comment by doktordirk** [comment]
should a least get a very basic test in for the milestone

**Comment by RWOverdijk** [comment]
Oehw interesting
