### ISSUE TITLE
On latest release

### ISSUE THREAD

**Issue by devenson** [SpoonX/aurelia-orm#72]
We are seeing this error on the latest aurelia-orm, aurelia-api and aurelia-authentication packages. 

system.js:4 Uncaught (in promise) Error: TypeError: (0 , _aureliaTemplating.customElement) is not a function
        at Object.eval (http://localhost:9000/jspm_packages/npm/aurelia-orm@2.2.2/component/association-select.js:75:100)
    Error loading http://localhost:9000/jspm_packages/npm/aurelia-orm@2.2.2/component/association-select.js

**Comment by doktordirk** [comment]
@RWOverdijk you need to publish 2.2.3 on npm. darn, that's why i ask if there is a hook

**Comment by doktordirk** [comment]
@devenson sorry. has nothing (not much) to to with our 'name change'. that's a stupid bug of mine and that npm seems to be behind. it's long fixed and published on github afaik

**Comment by doktordirk** [comment]
afaik fixed with https://github.com/SpoonX/aurelia-orm/commit/ae8a42d0367e9cd7610645dea07c510c4b408c72 and github relaase 2.2.3

**Comment by devenson** [comment]
@doktordirk - thanks. I'll check again when I have time to try the latest builds.

**Comment by doktordirk** [comment]
fixed: 2.2.3 is on npm
