### ISSUE TITLE
legacy reference to api

### ISSUE THREAD

**Issue by meash-nrel** [SpoonX/aurelia-orm#75]
Installing the latest aurelia-orm 2.2.3, it is loading github:spoonx/aurelia-api as a dependency.

This may be due to aurelia-authentication doing the same?
 https://github.com/SpoonX/aurelia-authentication/issues/109

I also see this reference to spoonx/aurelia-api in a /dist source:
https://github.com/SpoonX/aurelia-orm/blob/1b0798ed245d87719d82f86fa2cf7398ba8f09e3/dist/system/repository.js#L3

**Comment by doktordirk** [comment]
there is no new build / release yet with the mentioned change. should come soonish

**Comment by doktordirk** [comment]
see other issue
