### ISSUE TITLE
EntitysetData({}) not working as expected.

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#79]
@RWOverdijk 

```
  setData(data) {
    Object.assign(this, data);

    return this;
  }
```

when data = {} , nothing happens. while i guess that is intended, wasn't clear enough in the docs. also a method to reset en entitiy is then needed (one can use EntityManager.getEntity('xy') though for this

**Comment by RWOverdijk** [comment]
@doktordirk When data is empty, obviously you're not assigning any data.

As to resetting the entity, that might be tricky at this point. I would have to really make a copy of the entity (which I am not doing right now) and also associations wouldn't "work". If it has an ID, I _could_ implement a "sync" or something, to re-fetch the data for the entity.

I'm currently working on fixing dirty checking and saving for many associations. After that, I was planning on re-doing the whole state-checking mechanism. It needs more power :D
