### ISSUE TITLE
non descriptive getNewPopulatedEntity

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#82]
@RWOverdijk 
dump name. by name i'd expect it to be the same as getPopulatedEntity(data)  = make new entity and populates with data

**Comment by RWOverdijk** [comment]
That might be you then. It's documented, and has a different name for a reason. Naming goes well with getNewEntity().

**Comment by doktordirk** [comment]
right. i guess got confused since there is no  getEntity(data, entity). could be added for consistency

same for populateEntity(data) which could be added

on a related note. shouldn't getPopulatedEntity(data, entity) return a new entity instance no matter what?

**Comment by RWOverdijk** [comment]
I believe it does

**Comment by doktordirk** [comment]
``` js
  getPopulatedEntity(data, entity) {
    entity             = entity || this.getNewEntity();
//...
    return entity.setData(populatedData);
  }
```

that's the same entity. for a `getPopulatedEntity(data,entity)` i'd expect a new entity made of 'object.assign({},entity,data)`
