### ISSUE TITLE
EntityManager.getEntity not same as Repository.getNewEntity

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#83]
@RWOverdijk 
i'd expect those to do the same. EntityManager.getEntity however doesn't have repository meta set

**Comment by RWOverdijk** [comment]
@doktordirk Pretty sure you're doing something weird then.

https://github.com/SpoonX/aurelia-orm/blob/master/src/repository.js#L197

**Comment by doktordirk** [comment]
sortof did, but anyways:

i guess:
EntityManager.getEntity(Customer) ===  Repository.getNewEntity(Customer)

i did/know/expected?:
EntityManager.getEntity('customer') !==  Repository.getNewEntity('customer');

**Comment by RWOverdijk** [comment]
No, they're both a new instance. So it'll never be the same. However:

``` js
EntityManager.getEntity('customer').constructor !== Repository.getNewEntity('customer').constructor;
```

I think will be

**Comment by doktordirk** [comment]
i just meant like the same type. they return different stuff

**Comment by RWOverdijk** [comment]
Ah! I get what you're saying now.

A repository holds responsibility for a specific resource. That's why it doesn't accept an argument and uses the currently configured resource.
