### ISSUE TITLE
howto bind properties

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#85]
can't use properties in the view like customer.firstName

**Comment by RWOverdijk** [comment]
That has to work. That's one of the main things I'm doing with this module

**Comment by doktordirk** [comment]
What I mean that x.y as object has Getter/Setter on y. As entity it doesn't

**Comment by RWOverdijk** [comment]
Well, no. An entity is an entity. It should be the closest thing to a pojo to make it easy to work with. Do you have a code example?

**Comment by doktordirk** [comment]
the edit.js/html
https://github.com/doktordirk/aurelia-orm-loopback-sample/tree/test/client/src/modules/customer

**Comment by RWOverdijk** [comment]
And, then what doesn't work?

**Comment by doktordirk** [comment]
no UI feedback from customer whereas otherCustomer gets live UI feedback
