### ISSUE TITLE
convert isClean etc to getters

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#86]
can't be used in views like that. 
would be much easier if they'd be getters to enable `disabled.bind="product.isClean"`in views

**Comment by RWOverdijk** [comment]
I (again, sorry) disagree. I believe that checking should be done on save. It's more light weight, and makes more sense.

**Comment by doktordirk** [comment]
no problem if you disagree :smile: but i'm not sure you got my point

i guess, forms and submit buttons won't be rare. as of now, one needs:

in the vm

``` js
  get isUnchanged() {
    return this.product.isClean();
  }
```

in the v

``` html
<button class="btn btn-lg btn-success"
          click.delegate="update()"
          disabled.bind="isUnchanged">Update Information</button>
```

since that'll be a very common scenario, i propose to have:
in the vm

``` js
// nothing needed
  }
```

in the v

``` html
<button class="btn btn-lg btn-success"
          click.delegate="update()"
          disabled.bind="product.isClean">Update Information</button>
```
