### ISSUE TITLE
Thought about redux and GraphQL?

### ISSUE THREAD

**Issue by smolinari** [SpoonX/aurelia-orm#9]
This is a pretty interesting development, though have you seen redux and GraphQL? The GraphQL technology is pretty cool and redux as a store is super simple.

Scott

**Comment by RWOverdijk** [comment]
Hello @smolinari 

Thank you. The PR that I'm going to merge today has even more structure to it.

I have heard about those, but I haven't really worked with them yet. I'm not sure how they apply to this module. Don't they solve different problems? Perhaps you can explain to me what benefit they could bring this module.

What I wanted to make, was a simple but organized way to talk to my REST API. I have worked with a lot of ORM systems, in both PHP and Node and this is me trying to combine what I liked.

**Comment by smolinari** [comment]
GraphQL solves a lot of problems that come up with REST APIs. One of the most important one's is the issue of versioning. With GraphQL you have a single end point. It allows client applications to evolve completely independent of the backend. Another is multiple requests. GraphQL aggregates the queries needed and then sends it off to the server in a single package. Great for mobile. Plus, with GraphQL queries, you can have the components themselves (like in React JSX) query for the data they need. 

I am not a professional front end developer. But I do understand a lot of the concepts and issues with different technologies and GraphQL is an answer to a lot of web API issues. 

Here is some reading and viewing on GraphQL.

https://youtu.be/WQLzZf34FJ8?t=69

https://www.youtube.com/watch?v=Cfna8gwt9h8

https://youtu.be/9sc8Pyc51uU?t=16

https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html

Scott

**Comment by RWOverdijk** [comment]
Hello again @smolinari 

That sounds interesting, but as I expected solves a different problem. In most cases, I prefer working entity based. I'll dive into the resources you posted to educate myself further on the subject.

I'll close this ticket now as it doesn't apply to this repository.
