### ISSUE TITLE
consider (aurelia-)validatejs

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#96]
aurelia-validatejs https://github.com/aurelia/validatejs wraps https://validatejs.org/ for use in aurelia. this might be a saver way for validation oving forward

**Comment by pfurini** [comment]
Hi
I see you have a branch `greenkeeper-aurelia-validation-0.8.1`. Is it current or is it abandoned?

I don't want to add a dependency on the old aurelia-validation package, as I switched over a different validation solution. But given that the 0.8 version is now meant as a simple proxy over actual validation libs (like validatejs), I'm not against including it in my project..

Thx

PS: and, if I may suggest, try not to add an hard dependency over `aurelia-validatejs`, as it is not meant to be THE validation library, but one of the many that will come..

**Comment by RWOverdijk** [comment]
@nexbit good suggestions :) The idea is to not include _any_ validation library but in stead work with duck typing. We'll do this against the aurelia-validation wrapper, making it easy for you to provide your own. It's something that will have to be configured. I'm currently looking into this, but it's a bit tricky still.

**Comment by pfurini** [comment]
In the meantime I simply removed all validation stuff from my fork.. I'm not yet sure about the future of the base `aurelia-validation` plugin, cause its interface is not well crafted.
If it'll not improve in the next couple months, I suggest to simply get rid of the validation part as I've done in my fork, and create a separate plugin that can be used a bridge between orm and validation.

EDIT: to give you an insight of what I mean for `not well crafted`, there's currently no base interface for a generic validator, but only for a so-called `reporter`.. what the heck

**Comment by doktordirk** [comment]
not likely the validation gets sorted out quickly i think

**Comment by pfurini** [comment]
@doktordirk I share the same sentiment here.. It's really sad 'cause it's official, and that causes a lot of confusion among newcomers

**Comment by RWOverdijk** [comment]
Mhm... I feel tempted to hijack the project. It has potential, but it feels unstable to build against.

Anyway, we'll be solving it like I said earlier. Duck typing. We won't care what you use, as long as it has a `.validate()` method. _You_ decorate your entities, _you_ get the validator. So _we_ don't care. Then, if validatejs makes another "move", we can change our projects in stead. Feels safe to me :)

**Comment by pfurini** [comment]
Update on latest `aurelia-validation` announcement: maybe they're on the right track now, but I agree with @RWOverdijk, duck typing the validation methods are the way to go.
If the library of choice doesn't satisfy the interface, one needs a simple proxy to inject into the library.

**Comment by pfurini** [comment]
EDIT: sorry to gang-of-four.. An `adapter` not a proxy.. :-P

**Comment by doktordirk** [comment]
obsolete
